# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

#
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation;
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# Author: Muhammad Shadi Hajar  <m.hajar@rgu.ac.uk> <msh.syr@gmail.com>
#

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('trust', ['internet', 'config-store'])
    module.source = [
        'model/trust.cc',
        'helper/trust-helper.cc',
        'model/trust-node.cc',
        'model/trust-scheme.cc',
        'model/scheme-parameters.cc',
        'model/received-recommendations.cc',
        ]

    module_test = bld.create_ns3_module_test_library('trust')
    module_test.source = [
        'test/trust-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'trust'
    headers.source = [
        'model/trust.h',
        'helper/trust-helper.h',
        'model/trust-node.h',
        'model/trust-scheme.h',
        'model/scheme-parameters.h',
        'model/received-recommendations.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

